const actions = {
  HETHONGSP_GET_INIT_DATA_REQUEST: 'HETHONGSP_GET_INIT_DATA_REQUEST',
  HETHONGSP_GET_INIT_DATA_REQUEST_SUCCESS: 'HETHONGSP_GET_INIT_DATA_REQUEST_SUCCESS',
  HETHONGSP_GET_INIT_DATA_REQUEST_ERROR: 'HETHONGSP_GET_INIT_DATA_REQUEST_ERROR',
  getInitDataSP: (filterData) => {
    return (disPatch) => {
      //get role
      disPatch({
        type: actions.HETHONGSP_GET_INIT_DATA_REQUEST,
        payload: {filterData}
      });
    }
  },

  HETHONGSP_GET_LIST_REQUEST: 'HETHONGSP_GET_LIST_REQUEST',
  HETHONGSP_GET_LIST_REQUEST_SUCCESS: 'HETHONGSP_GET_LIST_REQUEST_SUCCESS',
  HETHONGSP_GET_LIST_REQUEST_ERROR: 'HETHONGSP_GET_LIST_REQUEST_ERROR',
  getListSP: (filterData) => ({
    type: actions.HETHONGSP_GET_LIST_REQUEST,
    payload: {filterData}
  }),

  HETHONG_GET_INIT_DATA_REQUEST: 'HETHONG_GET_INIT_DATA_REQUEST',
  HETHONG_GET_INIT_DATA_REQUEST_SUCCESS: 'HETHONG_GET_INIT_DATA_REQUEST_SUCCESS',
  HETHONG_GET_INIT_DATA_REQUEST_ERROR: 'HETHONG_GET_INIT_DATA_REQUEST_ERROR',
  getInitData: (filterData) => {
    return (disPatch) => {
      //get role
      disPatch({
        type: actions.HETHONG_GET_INIT_DATA_REQUEST,
        payload: {filterData}
      });
    }
  },

  HETHONG_GET_LIST_REQUEST: 'HETHONG_GET_LIST_REQUEST',
  HETHONG_GET_LIST_REQUEST_SUCCESS: 'HETHONG_GET_LIST_REQUEST_SUCCESS',
  HETHONG_GET_LIST_REQUEST_ERROR: 'HETHONG_GET_LIST_REQUEST_ERROR',
  getList: (filterData) => ({
    type: actions.HETHONG_GET_LIST_REQUEST,
    payload: {filterData}
  }),

  HETHONG_GET_CQ_REQUEST: 'HETHONG_GET_CQ_REQUEST',
  HETHONG_GET_CQ_REQUEST_SUCCESS: 'HETHONG_GET_CQ_REQUEST_SUCCESS',
  HETHONG_GET_CQ_REQUEST_ERROR: 'HETHONG_GET_CQ_REQUEST_ERROR',
  getCQ: () => ({
    type: actions.HETHONG_GET_CQ_REQUEST,
    payload: {}
  }),
};

export default actions;